# Generated by Django 5.1.4 on 2025-01-15 16:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('industry', models.CharField(choices=[('Frontend', 'Frontend Development'), ('Backend', 'Backend Development'), ('Mobile', 'Mobile Development'), ('Database', 'Database Management'), ('DevOps', 'DevOps'), ('AI/ML', 'Artificial Intelligence/Machine Learning'), ('Graphics', 'Graphics Design'), ('Digital Marketing', 'Digital Marketing')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
