# Generated by Django 5.1.4 on 2025-01-15 16:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('education', models.CharField(choices=[('CSIT', 'Computer Science and Information Technology'), ('BIT', 'Bachelor in Information Technology'), ('BCA', 'Bachelor in Computer Application'), ('BIM', 'Bachelor in Information Management')], max_length=10)),
                ('skills', models.JSONField(default=list)),
                ('experience', models.CharField(choices=[('6', '6 Months'), ('12', '12 Months'), ('18', '18 Months'), ('24', '24 Months')], max_length=3)),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
